#!/usr/bin/env bash
[[ "${DEBUG,,}" == "true" ]] && set -x

export HOME=/config

cd /config

FUNCTIONS="/scripts/functions.inc.sh"

. /usr/local/share/opam/opam-init/init.sh > /dev/null 2> /dev/null || true

umount /data/.Drive || umount -l /data/.Drive

sleep 5 && sv restart RCLONE_MOUNT_0 &

exec nice -n -10 google-drive-ocamlfuse -verbose -label FTIO -o allow_other -f /data/.Drive