#!/usr/bin/env bash
[[ "${DEBUG,,}" == "true" ]] && set -x

##ENVS###


##CODE### ALWAYS
ulimit -s unlimited

###CODE###
STARTUP_FUNCTIONS="/scripts/functions.inc.sh"
[[ -f $STARTUP_FUNCTIONS ]] && . $STARTUP_FUNCTIONS || { echo "ERROR: couldn't include ${STARTUP_FUNCTIONS}" && exit 1; }

[[ "${FIRST_RUN}" == "true" ]] && exit 0

echo "HISTCONTROL=ignoreboth" >>~/.bashrc
